#!/bin/bash

##

virtualenv --python=python3 ./venv

. venv/bin/activate

pip install -r requirements.txt

patch -p1 < ./vnet_router/rtr/patches/ncclient-debug.patch

##

if [ ! -f flowspy/settings.py ]; then
  cp -v flowspy/settings.py.dist flowspy/settings.py
fi

if [ ! -f flowspy/settings_local.py ]; then
  touch flowspy/settings_local.py
fi

##

