256: eth1@if257: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:3c:97:e3 brd ff:ff:ff:ff:ff:ff link-netnsid 1
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
258: eth3@if259: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:f9:b8:59 brd ff:ff:ff:ff:ff:ff link-netnsid 3
250: eth0@if251: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 02:42:ac:14:14:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
254: eth2@if255: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether aa:c1:ab:49:98:41 brd ff:ff:ff:ff:ff:ff link-netnsid 2
