#!/bin/bash

if [ "$1" = "--conf" ]; then
  shift 1
  
  shift_count=0
 
  if [ "$1" = "--myipv6" ]; then 
    shift 1
    myrouter_id__ipv6="$1"
    shift 1
    myrouter_ipv6="$1"
    shift 1
    myas__ipv6="$1"
    shift 1
    shift_count=$(( $shift_count + 4 ))
    
  fi

  myrouter_id="$1"
  shift 1
  myrouter_ip="$1"
  shift 1
  myas="$1"
  shift 1
  shift_count=$(( $shift_count + 3 ))
  
  ##
  
  [ -n "$myrouter_id" ] || myrouter_id="10.0.0.1"
  [ -n "$myrouter_ip" ] || myrouter_ip="10.0.0.1"
  [ -n "$myas" ] || myas="9991"
  
  ##
    
  echo "$0: myrouter_ip=$myrouter_ip myas=$myas myrouter_id=$myrouter_id" 1>&2
  echo "$0: myrouter_ipv6=$myrouter_ipv6 myas__ipv6=$myas__ipv6 myrouter_id__ipv6=$myrouter_id__ipv6" 1>&2
  
  ##
  
  #cat > /etc/exabgp/exabgp.conf <<EOF
  cat <<EOF
#neighbor 10.0.0.2 {
#	router-id 10.0.0.1;
#	local-address 10.0.0.1;
#	local-as 9991;
#
#	peer-as 9992;
#
#	family {
#            ipv4 unicast;
#            ipv4 multicast;
#            ipv4 nlri-mpls;
#            ipv4 mpls-vpn;
#            ipv4 flow;
#            ipv4 flow-vpn;
#            ipv6 unicast;
#            ipv6 flow;
#            ipv6 flow-vpn;
#	}
#
#	static {
#		route 10.4.0.0/32 next-hop self;
#	}
#}
EOF

  [ $# -gt 0 ] || set -- "10.0.0.2" "10.0.0.2" "9992"
  
  echo "$0: loop args: $*" 1>&2
  
  while [ $# -gt 0 ]; do

    is_ipv6=0
    if [ "$1" = "--ipv6" ]; then 
      shift 1
      shift_count=$(( $shift_count + 1 ))
      is_ipv6=1
    fi

    neighbor_id="$1" 
    shift 1
    shift_count=$(( $shift_count + 1 ))

    neighbor_ip="$1"
    shift 1
    shift_count=$(( $shift_count + 1 ))
    
    [ "$neighbor_ip" != "--" ] || break
  
    neighborAS="$1"
    shift 1
    shift_count=$(( $shift_count + 1 ))

    ##

if [ "$is_ipv6" = 0 ]; then
  #cat >> /etc/exabgp/exabgp.conf <<EOF
  cat <<EOF
#neighbor 10.0.0.3 
neighbor $neighbor_id {
	#router-id 10.0.0.1;
	router-id $myrouter_id;
	#local-address 10.0.0.1;
	local-address $myrouter_ip;
	#local-as 9991;
	local-as $myas;

	#peer-as 9993;
	peer-as $neighborAS;
        peer-address $neighbor_ip;

	#family {
	#    ipv4 unicast;
        #    #ipv4 multicast;
        #    #ipv4 nlri-mpls;
        #    #ipv4 mpls-vpn;
        #    #ipv4 flow;
        #    #ipv4 flow-vpn;
        #    #ipv6 unicast;
        #    #ipv6 flow;
        #    #ipv6 flow-vpn;
	#}

	static {
		route 10.10.0.0/32 next-hop self;
		route 10.100.0.0/32 next-hop self;
	}
}
EOF

else

  cat <<EOF
neighbor $neighbor_id {
	router-id $myrouter_id__ipv6;
	local-address $myrouter_ipv6;
	local-as $myas__ipv6;

	peer-as $neighborAS;
        peer-address $neighbor_ip;

	#family {
	#    ipv4 unicast;
        #    #ipv4 multicast;
        #    #ipv4 nlri-mpls;
        #    #ipv4 mpls-vpn;
        #    #ipv4 flow;
        #    #ipv4 flow-vpn;
        #    #ipv6 unicast;
        #    #ipv6 flow;
        #    #ipv6 flow-vpn;
	#}

	#static {
        #		route 10.10.0.0/32 next-hop self;
	#	route 10.100.0.0/32 next-hop self;
	#}
}
EOF

fi

  done

else

  mkdir /etc/exabgp/

  shift_count=0
  . "$0" --conf "$@" > /etc/exabgp/exabgp.conf
  shift "${shift_count}"

  ##

  mkfifo /run/exabgp.{in,out}
  chmod 0666 /run/exabgp.{in,out}
  chown exabgp: /run/exabgp.{in,out}

  ##

  if [ "$1" = "--bg" ]; then
    shift 1
    nohup exabgp --debug /etc/exabgp/exabgp.conf "$@" > exbgp.log 1>&2 &
  else
    #/fod_vnet_router --mnexec h1 exabgp --debug /etc/exabgp/exabgp.conf
    exec exabgp --debug /etc/exabgp/exabgp.conf "$@"
  fi

fi

