name: Docker Image CI

on:
  push:
    branches: [ "python3" ]
  pull_request:
    branches: [ "python3" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
     - name: Build the Docker image
     -  with:
            ref: feature/exabgp_support2
     -  run: docker build . --file ./Dockerfile.fod.debian-exabgp-and-tools --tag my-image-name1:$(date +%s)
